a = input('Digite algo: ')
print(type(a))
print('Tem Espaços? {}'.format(a.isspace()))
print('Tem somente números? {}'.format(a.isnumeric()))
print('Tem letras e números? {}'.format(a.isalnum()))
print('Tem somente letras? {}'.format(a.isalpha()))
print('Está em maiúsculo? {}'.format(a.isupper()))
print('Está em minúsculo? {}'.format(a.islower()))
print('Tem Maiúsculas e Minúsculas? {}'.format(a.title()))
